/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stdint.h"
#define  RCC_A    0x40021000
#define  GPIO_A   0x40010800
#define RCC_APB2ENR   *(volatile uint32_t *)  (RCC_A +0x18)
#define GPIO_CRH   *(volatile uint32_t *)  (GPIO_A +0x04)
#define GPIO_ODR     (GPIO_A +0x0c)
typedef volatile unsigned int  vuint32_t;
typedef union
{
	vuint32_t all_field;
	struct
	{
		vuint32_t  pin:13;
		vuint32_t  pin_13:1;
	}S_PIN;
}U_PIN_t;
volatile U_PIN_t * P_PIN =(volatile U_PIN_t *) GPIO_ODR
int main(void)
{
	RCC_APB2ENR |= 1<<2 ;
	GPIO_CRH &=0xff0ffff;
	GPIO_CRH |=0x00200000;
	int i ;
	while (1)
	{
		P_PIN ->S_PIN.pin_13=1;
		for (i=0;i<5000;i++);
		P_PIN ->S_PIN.pin_13=0;
		for (i=0;i<5000;i++);
	}
	return 0 ;
}

