/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f103x6_gpio_Driver.h"
#include "stm32f103xx.h"
#include  "lcd.h"
#include "KEYPAD.h"

//7segment numbers definitions
#define ZERO    0X01
#define ONE     0x79
#define TOW     0x24
#define THREE   0x30
#define FOUR    0x58
#define FIVE    0x12
#define SIX     0x02
#define SEVEN   0x39
#define EIGHT   0x00
#define NINE    0x10




void wait_ms()
{
	volatile uint32_t i ,j ;
	for(i=0 ; i<655 ; i++)
		for(j=0 ;j<60 ;j++)
			;
}
void Clock_init()
{
	//Enable Clock FOR (GPIOA)
	RCC_GPIOA_CLCK_ENABLE() ;
	//Enable Clock FOR (GPIOB)
	RCC_GPIOB_CLCK_ENABLE() ;
}
void  CONFIG_7_SEGMENT()
{
	GPIO_PIN_config_t pincnfg ;
	//configuration registers for port (b) from pin9 to pin15

	//OUTPUT PIN PUSH PULL
	pincnfg.GPIO_PIN_Numbers =GPIO_PIN_9 ;
	pincnfg.GPIO_PIN_MODE = PIN_MODE_OUT_PP ;
	pincnfg.GPIO_OUTPIN_Speed = PIN_OUT_SPEED_10 ;
	MCAL_GPIO_INIT(GPIOB, &pincnfg) ;


	pincnfg.GPIO_PIN_Numbers =GPIO_PIN_10 ;
	pincnfg.GPIO_PIN_MODE = PIN_MODE_OUT_PP ;
	pincnfg.GPIO_OUTPIN_Speed = PIN_OUT_SPEED_10 ;
	MCAL_GPIO_INIT(GPIOB, &pincnfg) ;

	pincnfg.GPIO_PIN_Numbers =GPIO_PIN_11 ;
	pincnfg.GPIO_PIN_MODE = PIN_MODE_OUT_PP ;
	pincnfg.GPIO_OUTPIN_Speed = PIN_OUT_SPEED_10 ;
	MCAL_GPIO_INIT(GPIOB, &pincnfg) ;


	pincnfg.GPIO_PIN_Numbers =GPIO_PIN_12 ;
	pincnfg.GPIO_PIN_MODE = PIN_MODE_OUT_PP ;
	pincnfg.GPIO_OUTPIN_Speed = PIN_OUT_SPEED_10 ;
	MCAL_GPIO_INIT(GPIOB, &pincnfg) ;

	pincnfg.GPIO_PIN_Numbers =GPIO_PIN_13 ;
	pincnfg.GPIO_PIN_MODE = PIN_MODE_OUT_PP ;
	pincnfg.GPIO_OUTPIN_Speed = PIN_OUT_SPEED_10 ;
	MCAL_GPIO_INIT(GPIOB, &pincnfg) ;

	pincnfg.GPIO_PIN_Numbers =GPIO_PIN_14 ;
	pincnfg.GPIO_PIN_MODE = PIN_MODE_OUT_PP ;
	pincnfg.GPIO_OUTPIN_Speed = PIN_OUT_SPEED_10 ;
	MCAL_GPIO_INIT(GPIOB, &pincnfg) ;

	pincnfg.GPIO_PIN_Numbers =GPIO_PIN_15 ;
	pincnfg.GPIO_PIN_MODE = PIN_MODE_OUT_PP ;
	pincnfg.GPIO_OUTPIN_Speed = PIN_OUT_SPEED_10 ;
	MCAL_GPIO_INIT(GPIOB, &pincnfg) ;


}
uint16_t SEGMENT_ARRAY[] ={ZERO , ONE , TOW , THREE , FOUR , FIVE , SIX , SEVEN , EIGHT , NINE ,ZERO};
char lcd_character[] ={'0' , '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' , '9' ,'10'};



void main(){
	Clock_init();
	LCD_init() ;
	CONFIG_7_SEGMENT();

	LCD_WRITE_STRING("	lets go !!!!!!");
	wait_ms(50);
	LCD_clear_screen();
	volatile uint32_t i ;
    for(i=0 ; i<11 ;i++)
    {
    	MCAL_GPIO_WritePort(GPIOB,SEGMENT_ARRAY[i]<<9);  // we shifted it because we write on pins from 9 to 15
    	LCD_WRITE_CHAR(lcd_character[i]);
    	wait_ms(11000);

    }



    LCD_clear_screen();
	KEYBAD_INIT() ;
	LCD_WRITE_CHAR('a');
	 LCD_clear_screen();

	char presskey ;
	//config_CRL_CRH();
	while (1)
	{

		presskey = KEYPAD_GET_CHAR();
		switch (presskey)
		{
		case ('!'):

					LCD_clear_screen();
		break ;

		case ('N'):

					break ;

		default:

			LCD_WRITE_CHAR(presskey);
			break;


		}


	}

}




