/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//LAB-2 stm32f103c6
// ENG:Ayman_Gamal
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
//addresses External interrupt EXTI0 GPIOAbin 0
#define  EXTI_BASE    (0x40010400)
#define  EXTI_IMR    *((volatile uint32_t*)(EXTI_BASE+0x00))
#define  EXTI_RTSR    *((volatile uint32_t*)(EXTI_BASE+0x08))
#define  EXTI_PR    *((volatile uint32_t*)(EXTI_BASE+0x14))
 //AFIO addresses
#define  AFIO_BASE    (0x40010000)
#define  AFIO_EXTICR1    *((volatile uint32_t*)(AFIO_BASE+0x08))
//RCC addresses
#define  RCC_BASE    (0x40021000)
#define  APP2ENR    *((volatile uint32_t*)(RCC_BASE+0x18))
//GPIO addresses
#define  GPIO_BASE   (0x40010800)
#define  GPIO_CRH    *((volatile uint32_t*)(GPIO_BASE+0x04))
#define  GPIOx_CRL    *((volatile uint32_t*)(GPIO_BASE+0x00))

#define GPIO_ODR     *((volatile uint32_t*)(GPIO_BASE+0x0C))
//NVIC
#define  NVIC_ISER0    *((volatile uint32_t*)(0xE000E100))

void Clock_init()  //Enable GPIOA and AFIO
{
	APP2ENR |=(1<<2);
	APP2ENR |=(1<<0);

}
void GPIOA_CON_INPUT_P0 ()
{
	GPIOx_CRL |=(1<<2);
}
void GPIOA_CON_OUTPUT_P13 ()
{
	GPIO_CRH &=0xff0fffff;
	GPIO_CRH |=0x00200000;
}


void main(){
	Clock_init();
	GPIOA_CON_INPUT_P0();
	GPIOA_CON_OUTPUT_P13();
	//select portA for exti0
	AFIO_EXTICR1=0x0;
	//select trigger rising
	EXTI_RTSR |=(1<<0);
	//Enable mask EXTI0
	EXTI_IMR |=(1<<0);
	//Enable mask NVIC IRQ 6 for EXTI0
	NVIC_ISER0 |=(1<<6);
	while(1){
		;

	}
}
void EXTI0_IRQHandler (void)
{
	// Toggle Pin 13
	GPIO_ODR ^= (1<<13);
  // Clear panding for interrupt panding from PR register (WTC)
	EXTI_PR |=(1<<0);
}
