/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stm32f103x6_USART_deriver.h>

#include "stdio.h"
#include "stdlib.h"
#include "stdint.h"
#include "stm32f103xx.h"
//#include "stm32f103x6_gpio_Driver.h"
#include "stm32f103x6_EXTI_DRIVER.h"
//#include "stm32f103x6_RCC_DRIVER.h"

#include "../../uart/HAL_DRIVER/INC/lcd.h"
#include "../../uart/HAL_DRIVER/INC/KEYPAD.h"



unsigned int IRQ_Flag = 0 ;
uint16_t ch ;

void UART_IRQ_Callback ()
{

    MCAL_UART_ReceiveData (USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);

}

int main(void)
{

	//Enable CLock
	RCC_GPIOA_CLOCK_ENABLE();
	RCC_GPIOB_CLOCK_ENABLE();
	RCC_AFIO_CLOCK_ENABLE();

	UART_Config uartCFG ;
	uartCFG.BaudRate = UART_BaudRate_115200 ;
	uartCFG.HwFlowCtl = UART_HwFlowCtl_NONE ;
	uartCFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE ;
	uartCFG.P_IRQ_CallBack = UART_IRQ_Callback ;
	uartCFG.Parity =UART_Parity__NONE ;
	uartCFG.Payload_Length = UART_Payload_Length_8B;
	uartCFG.StopBits = UART_StopBits__1 ;
	uartCFG.USART_Mode = UART_MODE_TX_RX ;

	MCAL_UART_Init(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins (USART1);

	/* Loop forever */





	while (1)
	{

	}
}

